- hosts: webservers
  remote_user: root
  
  tasks:
  
  - name: Install NRPE 
    apt: 
        name: "{{item}}" 
        state: present
    with_items:
       - nagios-plugins
       - nagios-nrpe-server
