- hosts: webservers
  remote_user: root
  
  tasks:
  
  - name: Install apache2
    apt: 
        name: "{{item}}" 
        state: present
    with_items:
       - apache2
       - mysql-server
       - php
       - php-mysql
       - libapache2-mod-php
       - php-mcrypt
       
  - name: Restart apache and mysql
    service:
         name: "{{item}}"
         state: started
    with_items:
       - apache2
       - mysql
